# Generated by Django 4.0.4 on 2022-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_remove_answer_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
