# Generated by Django 4.0.4 on 2022-07-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import ide.models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_answer_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='full_name',
            new_name='stud_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_id',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='mk_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=ide.models.upload_image, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='ans_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ide.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
