# Generated by Django 4.0.4 on 2022-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0004_rename_full_name_studentmarks_stud_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='mk_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
