# Generated by Django 4.0.4 on 2022-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_name', models.CharField(max_length=70)),
                ('admin_password', models.CharField(max_length=32)),
                ('admin_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_name', models.TextField(max_length=2000)),
                ('correct_answer', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
